version: "3.5"

services:
    php:
        container_name: php
        build: 
            context: .
        volumes:
            - ./app:/var/www/html/
        restart: always
        ports:
            - '8000:80'
        env_file: env_file